/**
 * <lang><zh-CN>BP 的应用自管运行时壳模型：声明四个主页面、生成本地化 tab 项，并把有限导航意图投影到 UniApp；不依赖原生标题、网络、身份或业务状态。</zh-CN><en>Application-owned runtime-shell model for the BP: declares four primary pages, creates localized tab items, and projects bounded navigation intents to UniApp; it depends on no native title, network, identity, or business state.</en></lang>
 * @lang zh-CN 微信端使用官方 custom tabBar 容器保持切换期间常驻；H5 隐藏 native surface 并由页面壳呈现 HIA-uView UTabbar，其他受支持宿主才可使用平台 label API。本模块只拥有固定路由和受限文案同步，不接受动态 URL。
 * @lang en WeChat uses the official custom-tab-bar container to remain mounted during switches; H5 hides the native surface and lets the page shell render HIA-uView UTabbar, while only other supported hosts may use platform label APIs. This module owns only fixed routes and bounded copy synchronization and accepts no dynamic URL.
 */

// <lang><zh-CN>复用唯一受限 UniApp API 解析入口；不在模块加载时捕获平台对象。</zh-CN><en>Reuse the sole bounded UniApp-API resolver and do not capture the platform object at module load.</en></lang>
import { resolveRuntimeUniApi } from './runtime-locale.mjs';

/**
 * <lang><zh-CN>向当前 UniApp 编译目标提交一个固定 tabBar item 更新。</zh-CN><en>Submits one fixed tabBar-item update to the current UniApp compilation target.</en></lang>
 * @param {object} payload <lang><zh-CN>由本模块生成的有限 index/text record。</zh-CN><en>Finite index/text record generated by this module.</en></lang>
 * @returns {unknown} <lang><zh-CN>平台调用结果；调用方不把它当作业务状态。</zh-CN><en>Platform-call result, which callers never treat as business state.</en></lang>
 * @lang zh-CN 显式兼容对象仅供 Node/旧宿主；H5 必须保留直接 `uni.setTabBarItem` 调用，让 UniApp 编译器注入真实 API，而不是读取 H5 的空 `globalThis.uni` 占位对象。
 * @lang en The explicit compatibility object serves only Node/legacy hosts; H5 must retain the direct `uni.setTabBarItem` call so the UniApp compiler injects the real API instead of reading H5's empty `globalThis.uni` placeholder.
 */
function setRuntimeTabBarItem(payload) {
  // <lang><zh-CN>只有显式暴露该方法的兼容对象才优先；空对象不得遮蔽编译器 API。</zh-CN><en>Only a compatibility object that explicitly exposes the method takes priority; an empty object must not shadow the compiler API.</en></lang>
  const compatibilityApi = resolveRuntimeUniApi();
  if (typeof compatibilityApi?.setTabBarItem === 'function') return compatibilityApi.setTabBarItem(payload);

  // <lang><zh-CN>直接属性调用是 UniApp 的编译边界；fail 回调只吸收平台拒绝，不改正文 locale 或业务状态。</zh-CN><en>The direct property call is the UniApp compilation boundary; the fail callback only absorbs a platform rejection and changes neither body locale nor business state.</en></lang>
  return uni.setTabBarItem({ ...payload, fail: () => {} });
}

/**
 * <lang><zh-CN>向当前 UniApp 编译目标提交隐藏原生 tabBar 的固定 H5 请求。</zh-CN><en>Submits the fixed H5 request to hide the native tab bar to the current UniApp compilation target.</en></lang>
 * @param {object} payload <lang><zh-CN>由本模块生成的无动画隐藏 record。</zh-CN><en>Nonanimated hide record generated by this module.</en></lang>
 * @returns {unknown} <lang><zh-CN>平台调用结果；调用方不把它当作渲染完成事实。</zh-CN><en>Platform-call result, which callers never treat as proof that rendering completed.</en></lang>
 * @lang zh-CN 显式兼容对象只供测试/旧宿主；真实 H5 保留直接 `uni.hideTabBar` 编译边界，失败回调不改 locale、路由或业务状态。
 * @lang en The explicit compatibility object serves only tests/legacy hosts; real H5 retains the direct `uni.hideTabBar` compile boundary, and failure changes no locale, route, or business state.
 */
function hideRuntimeTabBar(payload) {
  // <lang><zh-CN>只有真实暴露 hideTabBar 的兼容对象优先，空 H5 placeholder 不得遮蔽编译器 API。</zh-CN><en>Only a compatibility object that actually exposes hideTabBar takes priority; an empty H5 placeholder cannot shadow the compiler API.</en></lang>
  const compatibilityApi = resolveRuntimeUniApi();
  if (typeof compatibilityApi?.hideTabBar === 'function') return compatibilityApi.hideTabBar(payload);

  // <lang><zh-CN>直接 H5 API 只接收固定无动画请求；CSS 同时提供首帧与 API 失败兜底。</zh-CN><en>The direct H5 API receives only the fixed nonanimated request; CSS also supplies first-frame and API-failure fallback.</en></lang>
  return uni.hideTabBar({ ...payload, fail: () => {} });
}

/**
 * <lang><zh-CN>把固定主页面切换提交给当前 UniApp 编译目标。</zh-CN><en>Submits a fixed primary-page switch to the current UniApp compilation target.</en></lang>
 * @param {object} payload <lang><zh-CN>只含 allowlisted 本地 URL 的切换 record。</zh-CN><en>Switch record containing only an allowlisted local URL.</en></lang>
 * @returns {unknown} <lang><zh-CN>平台调用结果；不进入 locale 或业务 state。</zh-CN><en>Platform-call result that enters neither locale nor business state.</en></lang>
 * @lang zh-CN 兼容对象存在真实方法时复用它，否则保留直接编译器 API；不接受调用方拼接 URL。
 * @lang en Reuses a real method on a compatibility object when present and otherwise retains the direct compiler API; it accepts no caller-composed URL.
 */
function switchRuntimeTab(payload) {
  // <lang><zh-CN>空 H5 global placeholder 不满足方法 gate，因此不会阻断直接 API。</zh-CN><en>An empty H5 global placeholder fails the method gate and cannot block the direct API.</en></lang>
  const compatibilityApi = resolveRuntimeUniApi();
  if (typeof compatibilityApi?.switchTab === 'function') return compatibilityApi.switchTab(payload);

  // <lang><zh-CN>UniApp 编译器把固定 switch intent 适配到当前目标。</zh-CN><en>The UniApp compiler adapts the fixed switch intent to the current target.</en></lang>
  return uni.switchTab(payload);
}

/**
 * <lang><zh-CN>把固定 delta/fallback 返回意图提交给当前 UniApp 编译目标。</zh-CN><en>Submits a fixed delta/fallback back intent to the current UniApp compilation target.</en></lang>
 * @param {object} payload <lang><zh-CN>由本模块生成的 delta=1 与受限 fail callback。</zh-CN><en>Module-generated delta-one value and bounded fail callback.</en></lang>
 * @returns {unknown} <lang><zh-CN>平台调用结果；不成为导航授权。</zh-CN><en>Platform-call result that never becomes navigation authority.</en></lang>
 * @lang zh-CN 直接调用只解决 H5 API 注入，不扩大 route allowlist 或页面输入。
 * @lang en The direct call only enables H5 API injection and expands neither the route allowlist nor page input.
 */
function navigateRuntimeBack(payload) {
  // <lang><zh-CN>真实兼容方法优先，避免测试或显式宿主适配被编译目标覆盖。</zh-CN><en>A real compatibility method takes priority so a test or explicit host adapter is not overwritten by the compilation target.</en></lang>
  const compatibilityApi = resolveRuntimeUniApi();
  if (typeof compatibilityApi?.navigateBack === 'function') return compatibilityApi.navigateBack(payload);

  // <lang><zh-CN>直接编译器 API 只接收本模块已经限制的 payload。</zh-CN><en>The direct compiler API receives only the payload already bounded by this module.</en></lang>
  return uni.navigateBack(payload);
}

/**
 * <lang><zh-CN>生产环境使用的冻结 UniApp chrome adapter。</zh-CN><en>Frozen UniApp chrome adapter used in production.</en></lang>
 * @lang zh-CN 四项方法都保留 direct UniApp 调用以支持目标编译；测试仍可按函数参数注入更窄替身。
 * @lang en All four methods retain direct UniApp calls for target compilation; tests may still inject narrower doubles through function parameters.
 */
const RUNTIME_CHROME_UNI_API = Object.freeze({
  hideTabBar: hideRuntimeTabBar,
  setTabBarItem: setRuntimeTabBarItem,
  switchTab: switchRuntimeTab,
  navigateBack: navigateRuntimeBack
});

/**
 * <lang><zh-CN>四个主页面的冻结应用壳声明。</zh-CN><en>Frozen application-shell declarations for the four primary pages.</en></lang>
 * @lang zh-CN value、message key 和本地 URL 都由第一方源码固定，不能由 manifest、query、远端数据或用户输入扩展。
 * @lang en Values, message keys, and local URLs are fixed by first-party source and cannot be extended by a manifest, query, remote data, or user input.
 */
export const PRIMARY_PAGE_SPECS = Object.freeze([
  Object.freeze({ value: 'home', labelKey: 'nav.home', titleKey: 'title.home', url: '/pages/home/index' }),
  Object.freeze({ value: 'discover', labelKey: 'nav.discover', titleKey: 'title.discover', url: '/pages/discover/index' }),
  Object.freeze({ value: 'reservations', labelKey: 'nav.reservations', titleKey: 'title.reservations', url: '/pages/reservations/index' }),
  Object.freeze({ value: 'profile', labelKey: 'nav.profile', titleKey: 'title.profile', url: '/pages/profile/index' })
]);

/**
 * <lang><zh-CN>按主页面 value 建立的只读有限查找表。</zh-CN><en>Readonly finite lookup table keyed by primary-page value.</en></lang>
 * @lang zh-CN 查找表只从同文件冻结声明生成，避免调用方提供 URL 或将未知 tab 当成页面。
 * @lang en The lookup is created only from frozen declarations in this file, preventing callers from supplying URLs or treating an unknown tab as a page.
 */
const PRIMARY_PAGE_BY_VALUE = Object.freeze(Object.fromEntries(PRIMARY_PAGE_SPECS.map((pageSpec) => [pageSpec.value, pageSpec])));

/**
 * <lang><zh-CN>判断一个未知值是否为应用声明的主页面。</zh-CN><en>Determines whether an unknown value is an application-declared primary page.</en></lang>
 * @param {unknown} value <lang><zh-CN>待验证的 tab/page value。</zh-CN><en>Tab/page value to validate.</en></lang>
 * @returns {boolean} <lang><zh-CN>仅在有限声明中存在时为 true。</zh-CN><en>True only when present in the finite declaration.</en></lang>
 * @lang zh-CN 本函数不规范化、拼接或猜测未知值。
 * @lang en This function does not normalize, concatenate, or guess an unknown value.
 */
export function isPrimaryPage(value) {
  // <lang><zh-CN>只有 string 且为查找表自有键时才通过，拒绝原型链与隐式类型转换。</zh-CN><en>Pass only a string that is an own lookup key, rejecting prototype-chain and implicit type coercion.</en></lang>
  return typeof value === 'string' && Object.hasOwn(PRIMARY_PAGE_BY_VALUE, value);
}

/**
 * <lang><zh-CN>从当前 runtime translator 生成平台/HIA-uView tab chrome 共用的单语言 items。</zh-CN><en>Creates single-language items shared by platform and HIA-uView tab chrome from the current runtime translator.</en></lang>
 * @param {(messageKey: string) => string} translate <lang><zh-CN>唯一 runtime locale store 的静态资源翻译函数。</zh-CN><en>Static-resource translator from the sole runtime locale store.</en></lang>
 * @returns {ReadonlyArray<{value: string, label: string}>} <lang><zh-CN>固定顺序的冻结 tab 项。</zh-CN><en>Frozen tab items in fixed order.</en></lang>
 * @lang zh-CN label key 来自第一方声明；translate 不接收路由、query、领域对象或远端数据。
 * @lang en Label keys come from first-party declarations; translate receives no route, query, domain object, or remote data.
 */
export function createPrimaryTabItems(translate) {
  // <lang><zh-CN>缺少 translator 时返回空冻结列表，使展示层安全不呈现未知或默认混排文案。</zh-CN><en>Return an empty frozen list when the translator is absent so the presentation layer safely renders no unknown or mixed default copy.</en></lang>
  if (typeof translate !== 'function') return Object.freeze([]);

  // <lang><zh-CN>逐项只投影稳定 value 与当前 locale label，不暴露内部 URL 给 UI 组件。</zh-CN><en>Project only stable values and current-locale labels, exposing no internal URL to the UI component.</en></lang>
  return Object.freeze(PRIMARY_PAGE_SPECS.map((pageSpec) => Object.freeze({
    value: pageSpec.value,
    label: translate(pageSpec.labelKey)
  })));
}

/**
 * <lang><zh-CN>读取当前微信页面栈，供 custom tabBar 的页面实例同步使用。</zh-CN><en>Reads the current WeChat page stack for custom-tabBar page-instance synchronization.</en></lang>
 * @returns {unknown[]} <lang><zh-CN>可用页面数组；宿主缺失或读取失败时为空数组。</zh-CN><en>Available page array, or an empty array when the host is absent or reading fails.</en></lang>
 * @lang zh-CN 本函数只调用无参数 `getCurrentPages`，不读取页面 data、query、referrer 或用户内容。
 * @lang en This function calls only zero-argument `getCurrentPages` and reads no page data, query, referrer, or user content.
 */
function readCurrentPageStack() {
  try {
    // <lang><zh-CN>优先使用小程序模块级全局函数；兼容测试或 H5 显式提供的 global fallback。</zh-CN><en>Prefer the Mini Program module-level global and support an explicit global fallback for tests or H5.</en></lang>
    const readPages = typeof getCurrentPages === 'function' ? getCurrentPages : globalThis.getCurrentPages;
    const pages = typeof readPages === 'function' ? readPages() : [];
    return Array.isArray(pages) ? pages : [];
  } catch {
    return [];
  }
}

/**
 * <lang><zh-CN>按 UniApp 编译目标判断当前宿主是否拥有微信 custom-tab-bar 页面实例语义。</zh-CN><en>Determines from the UniApp compilation target whether the current host has WeChat custom-tab-bar page-instance semantics.</en></lang>
 * @param {{ weChat?: boolean }} adapters <lang><zh-CN>测试可注入的显式平台判定。</zh-CN><en>Explicit platform determination injectable by tests.</en></lang>
 * @returns {boolean} <lang><zh-CN>仅真实微信小程序或显式测试替身返回 true。</zh-CN><en>True only for a real WeChat Mini Program or explicit test double.</en></lang>
 * @lang zh-CN 使用 UniApp 官方编译平台常量，不从 `wx`、`window`、UA 或设备信息猜测平台；Node 未声明该常量时稳定落到非微信值。
 * @lang en Uses UniApp's official compiled-platform constant and never guesses the platform from `wx`, `window`, user agent, or device information; Node deterministically lands on the non-WeChat value when the constant is undeclared.
 */
function isWeChatCustomTabBarRuntime(adapters) {
  // <lang><zh-CN>显式测试判定始终优先，避免 Node 全局状态影响单元测试。</zh-CN><en>An explicit test determination always takes priority, preventing Node global state from affecting unit tests.</en></lang>
  if (typeof adapters.weChat === 'boolean') return adapters.weChat;

  // <lang><zh-CN>UniApp/Vite 将官方常量编译为目标字面量；`.mjs` 不再依赖该工具链未处理的 `#ifdef` 注释。</zh-CN><en>UniApp/Vite compiles the official constant into a target literal; the `.mjs` module no longer depends on `#ifdef` comments that this toolchain does not process there.</en></lang>
  return process.env.UNI_PLATFORM === 'mp-weixin';
}

/**
 * <lang><zh-CN>按 UniApp 编译目标判断当前宿主是否使用 H5 应用自管 HIA-uView 主导航。</zh-CN><en>Determines from the UniApp compilation target whether the current host uses the H5 application-owned HIA-uView primary navigation.</en></lang>
 * @param {{ h5?: boolean }} adapters <lang><zh-CN>测试可注入的显式 H5 判定。</zh-CN><en>Explicit H5 determination injectable by tests.</en></lang>
 * @returns {boolean} <lang><zh-CN>仅真实 H5 构建或显式测试替身返回 true。</zh-CN><en>True only for a real H5 build or an explicit test double.</en></lang>
 * @lang zh-CN 使用 UniApp 官方编译平台常量，不读取 DOM、UA、wx 全局或设备信息；Node 未声明该常量时稳定落到 false。
 * @lang en Uses UniApp's official compiled-platform constant and reads no DOM, user agent, wx global, or device information; Node deterministically lands on false when the constant is undeclared.
 */
function isH5ApplicationTabRuntime(adapters) {
  // <lang><zh-CN>显式测试事实优先，避免 Node 全局或构建工具模拟状态影响用例。</zh-CN><en>An explicit test fact takes priority, preventing Node globals or build-tool simulation state from affecting a case.</en></lang>
  if (typeof adapters.h5 === 'boolean') return adapters.h5;

  // <lang><zh-CN>只消费编译目标字面量；其他宿主不会因兼容全局误入 H5 分支。</zh-CN><en>Consume only the compiled-target literal; another host cannot enter the H5 branch through a compatibility global.</en></lang>
  return process.env.UNI_PLATFORM === 'h5';
}

/**
 * <lang><zh-CN>同步当前主页面、locale、单语言标题与四项 label 到目标宿主采用的主导航 chrome。</zh-CN><en>Synchronizes the current primary page, locale, single-language title, and four labels into the primary-navigation chrome adopted by the target host.</en></lang>
 * @param {unknown} pageValue <lang><zh-CN>第一方主页面 value。</zh-CN><en>First-party primary-page value.</en></lang>
 * @param {unknown} locale <lang><zh-CN>共享 runtime locale 的候选值。</zh-CN><en>Candidate value from the shared runtime locale.</en></lang>
 * @param {(messageKey: string) => string} translate <lang><zh-CN>共享 runtime translator。</zh-CN><en>Shared runtime translator.</en></lang>
 * @param {{ pages?: unknown[], uniApi?: unknown, documentApi?: unknown, weChat?: boolean, h5?: boolean }} [adapters] <lang><zh-CN>测试可注入的受限宿主替身。</zh-CN><en>Bounded host doubles injectable by tests.</en></lang>
 * @returns {boolean} <lang><zh-CN>微信 custom 更新、H5 native 隐藏或其他宿主 label 更新是否被同步接受。</zh-CN><en>Whether the WeChat custom update, H5 native hide, or another host's label update was accepted synchronously.</en></lang>
 * @lang zh-CN 微信优先调用当前 tab 页的 `getTabBar().setData`；H5 每次一级页 onShow 重试隐藏 native tab，标签由响应式 HIA-uView adapter 呈现；其他非微信宿主才逐项尝试 `setTabBarItem`。
 * @lang en WeChat first calls the current tab page's `getTabBar().setData`; H5 retries hiding the native tab on every primary-page show while the reactive HIA-uView adapter renders labels; only other non-WeChat hosts try `setTabBarItem` item by item.
 */
export function syncPrimaryTabChrome(pageValue, locale, translate, adapters = {}) {
  // <lang><zh-CN>主页面与 translator 必须同时通过有限 gate，未知输入不得触达平台。</zh-CN><en>The primary page and translator must both pass finite gates; unknown input never reaches the platform.</en></lang>
  if (!isPrimaryPage(pageValue) || typeof translate !== 'function') return false;

  // <lang><zh-CN>先依据编译目标选择互斥 platform 分支，避免 H5 compatibility page 暴露同名方法时误入微信 custom lifecycle。</zh-CN><en>Select the mutually exclusive platform branch from the compile target first, preventing an H5 compatibility page with similarly named methods from entering the WeChat custom lifecycle.</en></lang>
  const isWeChat = isWeChatCustomTabBarRuntime(adapters);
  const isH5 = isH5ApplicationTabRuntime(adapters);

  if (isWeChat) {
    // <lang><zh-CN>custom tabBar 只区分当前支持的两个 canonical locale，其他值确定性回退简体中文。</zh-CN><en>The custom tab bar distinguishes only the two supported canonical locales and deterministically falls back to Simplified Chinese.</en></lang>
    const canonicalLocale = locale === 'en' ? 'en' : 'zh-Hans';
    // <lang><zh-CN>页面栈只在微信分支读取；H5 与其他目标不探测 `getTabBar`。</zh-CN><en>Read the page stack only in the WeChat branch; H5 and other targets never probe `getTabBar`.</en></lang>
    const pages = Array.isArray(adapters.pages) ? adapters.pages : readCurrentPageStack();

    // <lang><zh-CN>微信每个 tab 页拥有自己的 official custom-tab-bar 实例；在 onShow 更新当前实例可保持常驻并校正选中态。</zh-CN><en>Each WeChat tab page owns its official custom-tab-bar instance; updating the current instance on show retains the chrome and corrects selection.</en></lang>
    try {
      const currentPage = pages.at(-1);
      const customTabBar = typeof currentPage?.getTabBar === 'function' ? currentPage.getTabBar() : null;
      if (typeof customTabBar?.setData === 'function') {
        customTabBar.setData({ selected: pageValue, locale: canonicalLocale });
        return true;
      }
      // <lang><zh-CN>实例尚未就绪时保持安全无操作，避免退回会被 tourist appid 拒绝的 native API。</zh-CN><en>Remain a safe no-op while the instance is not ready, avoiding fallback to native APIs rejected by a tourist appid.</en></lang>
      return false;
    } catch {
      return false;
    }
  }

  // <lang><zh-CN>H5 的可见 label 由共享 locale 驱动的 UTabbar 直接呈现；这里只在 tab 页已就绪的 onShow 重试隐藏 native surface。</zh-CN><en>H5 visible labels are rendered directly by the shared-locale-driven UTabbar; this branch only retries hiding the native surface after the tab page is ready on show.</en></lang>
  const uniApi = adapters.uniApi ?? RUNTIME_CHROME_UNI_API;
  if (isH5) {
    // <lang><zh-CN>缓存的 H5 tab 页都会保留组件实例，因此只允许当前页 onShow 路径写文档标题；根语言由共享 locale 的页面壳 effect 同步。</zh-CN><en>Cached H5 tab pages retain their component instances, so only the current page's onShow path may write the document title; the page-shell effect synchronizes the root language from the shared locale.</en></lang>
    const documentApi = adapters.documentApi ?? globalThis.document;
    // <lang><zh-CN>title key 来自冻结页面声明，translator 只返回当前语言静态文案；缺失 document 的非浏览器测试/宿主安全跳过。</zh-CN><en>The title key comes from the frozen page declaration and the translator returns only current-language static copy; a nonbrowser test or host without a document safely skips it.</en></lang>
    if (documentApi && typeof documentApi === 'object' && 'title' in documentApi) documentApi.title = translate(PRIMARY_PAGE_BY_VALUE[pageValue].titleKey);

    // <lang><zh-CN>缺失 hide API 时报告未接受，静态 CSS 仍保证不出现双栏和遗留占位。</zh-CN><en>Report nonacceptance when the hide API is absent; static CSS still prevents dual bars and stale reserved space.</en></lang>
    if (typeof uniApi?.hideTabBar !== 'function') return false;
    try {
      // <lang><zh-CN>固定 animation=false；API success/fail 均不成为页面或业务事实。</zh-CN><en>Fix animation to false; neither API success nor failure becomes a page or business fact.</en></lang>
      uniApi.hideTabBar({ animation: false });
      return true;
    } catch {
      return false;
    }
  }

  // <lang><zh-CN>其他非微信、非 H5 宿主可继续使用已声明 tabBar 的公开 API 更新四项文案；任何异常都不影响正文 locale。</zh-CN><en>Other non-WeChat, non-H5 hosts may continue updating four labels through the declared tab-bar API; any exception leaves body locale unchanged.</en></lang>
  if (typeof uniApi?.setTabBarItem !== 'function') return false;
  try {
    createPrimaryTabItems(translate).forEach((item, index) => uniApi.setTabBarItem({ index, text: item.label }));
    return true;
  } catch {
    return false;
  }
}

/**
 * <lang><zh-CN>以接近原生 tab 的语义打开一个固定主页面。</zh-CN><en>Opens a fixed primary page with semantics close to a native tab.</en></lang>
 * @param {unknown} pageValue <lang><zh-CN>来自受控 tab chrome 或第一方页面 action 的候选 value。</zh-CN><en>Candidate value from controlled tab chrome or a first-party page action.</en></lang>
 * @param {unknown} [uniApi] <lang><zh-CN>可选 UniApp API 对象，用于运行时调用或测试替身。</zh-CN><en>Optional UniApp API object for runtime calls or a test double.</en></lang>
 * @returns {boolean} <lang><zh-CN>导航是否被同步接受。</zh-CN><en>Whether navigation was accepted synchronously.</en></lang>
 * @lang zh-CN `switchTab` 只委托平台切换已声明一级路由；微信 official custom tabBar 的常驻由宿主负责，H5 可见 UTabbar 由目标页面壳重建，共享 demo state 始终由应用级 module store 持有。
 * @lang en `switchTab` delegates only switching among declared primary routes; the host retains WeChat's official custom tab bar, the destination page shell recreates the visible H5 UTabbar, and the application-level module store always owns shared demo state.
 */
export function openPrimaryPage(pageValue, uniApi = RUNTIME_CHROME_UNI_API) {
  // <lang><zh-CN>先验证有限 value，再读取固定 URL；未知输入绝不进入平台 API。</zh-CN><en>Validate the finite value before reading its fixed URL; unknown input never reaches the platform API.</en></lang>
  if (!isPrimaryPage(pageValue) || typeof uniApi?.switchTab !== 'function') return false;

  // <lang><zh-CN>平台同步异常只使本次导航失败，不改写 locale、业务状态或其他路由。</zh-CN><en>A synchronous platform exception only fails this navigation and rewrites no locale, business state, or other route.</en></lang>
  try {
    uniApi.switchTab({ url: PRIMARY_PAGE_BY_VALUE[pageValue].url });
    return true;
  } catch {
    return false;
  }
}

/**
 * <lang><zh-CN>尝试返回上一页，并在页面栈不可返回时打开固定主页面。</zh-CN><en>Attempts to return to the previous page and opens a fixed primary page when the stack cannot go back.</en></lang>
 * @param {unknown} fallbackPageValue <lang><zh-CN>页面源码声明的有限 fallback 主页面 value。</zh-CN><en>Finite fallback primary-page value declared by page source.</en></lang>
 * @param {unknown} [uniApi] <lang><zh-CN>可选 UniApp API 对象，用于运行时调用或测试替身。</zh-CN><en>Optional UniApp API object for runtime calls or a test double.</en></lang>
 * @returns {boolean} <lang><zh-CN>返回或 fallback 是否被同步接受。</zh-CN><en>Whether back or fallback was accepted synchronously.</en></lang>
 * @lang zh-CN 回退始终为 delta=1；异步 fail 回调只能进入同一固定主页面 allowlist。
 * @lang en Back is always delta=1; the asynchronous fail callback can enter only the same fixed primary-page allowlist.
 */
export function navigateBackOrOpenPrimaryPage(fallbackPageValue, uniApi = RUNTIME_CHROME_UNI_API) {
  // <lang><zh-CN>无 navigateBack 时直接执行受限 fallback，适配从分享/刷新直接进入的页面。</zh-CN><en>When navigateBack is unavailable, run the bounded fallback directly, accommodating pages entered from a share or refresh.</en></lang>
  if (typeof uniApi?.navigateBack !== 'function') return openPrimaryPage(fallbackPageValue, uniApi);

  // <lang><zh-CN>把异步失败处理收敛为同一 allowlisted helper，且同步异常同样进入该 fallback。</zh-CN><en>Constrain asynchronous failure handling to the same allowlisted helper, and route a synchronous exception to that fallback as well.</en></lang>
  try {
    uniApi.navigateBack({
      delta: 1,
      fail: () => openPrimaryPage(fallbackPageValue, uniApi)
    });
    return true;
  } catch {
    return openPrimaryPage(fallbackPageValue, uniApi);
  }
}
